apiVersion: v1
kind: Service
metadata:
  name: ngnix-service
  labels:
   app: ngnix
   namespace: default
spec:
  selector:
    app: ngnix
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
