apiVersion: v1
kind: Service
metadata:
  name: nginx-service-svc
  labels:
   app: nginx
   namespace: default
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
